# Generated by Django 6.1 on 2026-08-27 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pilgrim', 'Pilgrim / Warkari'), ('admin', 'Admin / Seva Team')], default='pilgrim', max_length=20)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('organization', models.CharField(blank=True, max_length=150, null=True)),
                ('dindi_number', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('reset_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('reset_otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
