# Generated by Django 6.1 on 2026-08-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='squad_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('pilgrim', 'Pilgrim / Warkari'), ('volunteer', 'Volunteer / Sevekar'), ('admin', 'Admin / Seva Team')], default='pilgrim', max_length=20),
        ),
    ]
