# Generated by Django 6.1 on 2026-08-30

from django.db import migrations


class Migration(migrations.Migration):
    """Merge the Firebase UID and volunteer-profile migration branches."""

    dependencies = [
        ('accounts', '0002_userprofile_firebase_uid'),
        ('accounts', '0003_userprofile_approval_status_userprofile_approved_at_and_more'),
    ]

    operations = []
