# Generated by Django 6.1 on 2026-08-29 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('name_mr', models.CharField(blank=True, max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('boundary_geojson', models.JSONField(blank=True, null=True)),
                ('max_safe_capacity', models.IntegerField(default=50000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_count', models.IntegerField()),
                ('status', models.CharField(choices=[('DEPLOYED', 'Deployed'), ('EN_ROUTE', 'En Route'), ('ACTIVE', 'Active on Ground')], default='DEPLOYED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='crowdflow.zone')),
            ],
            options={
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='CrowdDensityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_count', models.IntegerField()),
                ('density_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('source', models.CharField(choices=[('crowdvision', 'CrowdVision Camera'), ('simulated', 'Simulated Stream')], default='simulated', max_length=30)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='density_readings', to='crowdflow.zone')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CrowdAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('risk_score', models.IntegerField(default=85)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('action_type', models.CharField(default='Deploy', max_length=50)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_alerts', to='crowdflow.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneCapacityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('risk_score', models.IntegerField(default=15)),
                ('movement_direction', models.CharField(default='Forward', max_length=100)),
                ('movement_speed_kmh', models.FloatField(default=3.5)),
                ('trend', models.CharField(choices=[('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('stable', 'Stable')], default='stable', max_length=20)),
                ('last_breach_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_status', to='crowdflow.zone')),
            ],
        ),
    ]
