# Generated by Django 6.0.3 on 2026-08-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_sosreport_admin_alter_sosreport_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosreport',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('acknowledged', 'ACKNOWLEDGED / RESPONDED'), ('resolved', 'RESOLVED'), ('open', 'ACTIVE')], default='active', max_length=30),
        ),
    ]
