# Generated by Django 6.1 on 2026-08-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='Ringan Ground', max_length=150)),
                ('density_level', models.CharField(choices=[('NORMAL', 'Level 1: Normal Flow (सुरळीत)'), ('MODERATE', 'Level 2: Moderate Crowd (मध्यम)'), ('HEAVY', 'Level 3: Heavy Congestion (दाट गर्दी)'), ('CRITICAL', 'Level 4: Bottleneck Warning (गंभीर)')], default='NORMAL', max_length=20)),
                ('flow_speed', models.CharField(default='Smooth flow (4.0 km/h)', max_length=100)),
                ('recommended_action', models.CharField(default='Normal pilgrim movement. Maintain discipline in Dindi lines.', max_length=200)),
                ('active_volunteers_count', models.IntegerField(default=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('MEDICAL', 'Medical Emergency / रुग्णवाहिका'), ('LOST_PERSON', 'Lost Person / हरवलेली व्यक्ती'), ('CROWD_DENSITY', 'Crowd Stampede Risk / गर्दी नियंत्रण'), ('ACCIDENT', 'Road Accident / अपघात'), ('GENERAL', 'Urgent Assistance / मदत हवी आहे')], default='MEDICAL', max_length=30)),
                ('caller_name', models.CharField(max_length=150)),
                ('caller_phone', models.CharField(max_length=20)),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('DISPATCHED', 'Rescue Unit Dispatched'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium')], default='HIGH', max_length=20)),
                ('dispatched_unit', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PalkhiLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palkhi_name', models.CharField(default='Sant Dnyaneshwar Maharaj Palkhi', max_length=150)),
                ('palkhi_name_mr', models.CharField(default='श्री संत ज्ञानेश्वर महाराज पालखी', max_length=150)),
                ('current_stop', models.CharField(default='Saswad Checkpoint', max_length=150)),
                ('current_stop_mr', models.CharField(default='सासवड चेकपॉईंट', max_length=150)),
                ('next_stop', models.CharField(default='Jejuri Pavan Khind', max_length=150)),
                ('next_stop_mr', models.CharField(default='जेजुरी पावनखिंड', max_length=150)),
                ('latitude', models.FloatField(default=18.3444)),
                ('longitude', models.FloatField(default=74.0305)),
                ('status', models.CharField(choices=[('LIVE', 'Live Moving'), ('HALTED', 'Temporary Halt / Visava'), ('NIGHT_STAY', 'Night Stay / Mukkam')], default='LIVE', max_length=20)),
                ('distance_covered_km', models.FloatField(default=68.5)),
                ('total_distance_km', models.FloatField(default=245.0)),
                ('eta_next_stop', models.CharField(default='2 hrs 15 mins', max_length=50)),
                ('schedule_status', models.CharField(default='12.4 km ahead of schedule', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SevaResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_mr', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('MEDICAL', 'Medical Camp & Ambulance'), ('WATER', 'Clean Drinking Water Point'), ('FOOD', 'Annachatra / Mahaprasad'), ('SHELTER', 'Night Shelter & Tent Ground'), ('SANITATION', 'Mobile Toilets & Sanitation')], default='WATER', max_length=30)),
                ('location_name', models.CharField(max_length=200)),
                ('distance_meters', models.IntegerField(default=350)),
                ('contact_number', models.CharField(default='108', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity_or_supplies', models.CharField(default='Full Stock / Open', max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
