# Generated by Django 6.1 on 2026-08-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wari_core', '0002_group_groupmessage_messagereport_groupmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('FOOD', 'Food / Annachatra'), ('WATER', 'Water Point'), ('TOILETS', 'Toilets'), ('RESTROOMS', 'Restrooms'), ('MEDICAL', 'Medical Camp')], max_length=20)),
                ('location_name', models.CharField(help_text='Palkhi stop place name (e.g. Alandi, Jejuri)', max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('label', models.CharField(blank=True, default='', help_text='Optional custom label from admin', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
