# Generated by Django 6.1 on 2026-08-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wari_core', '0003_nearbyresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageDustbin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_mr', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('ORGANIC_DRY', 'Wet & Dry Dual Bins / ओला व सुका कचरा'), ('PLASTIC_ONLY', 'Plastic Bottle Crusher & Collector / प्लॅस्टिक संकलन'), ('BIO_MEDICAL', 'Sanitary & Medical Waste / वैद्यकीय कचरा'), ('COMMUNITY_COMPACTOR', 'Community Mega Compactor / मोठा संकलन केंद्र')], default='ORGANIC_DRY', max_length=30)),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(default=18.3444)),
                ('longitude', models.FloatField(default=74.0305)),
                ('capacity_liters', models.IntegerField(default=240)),
                ('fill_level_percent', models.IntegerField(default=25)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational / चालू'), ('NEEDS_EMPTYING', 'Nearly Full / साफ करणे आवश्यक'), ('OVERFLOWING', 'Overflow Alert / कचरा भरला आहे'), ('CLEANED', 'Recently Cleaned / नुकतेच स्वच्छ केले')], default='OPERATIONAL', max_length=20)),
                ('assigned_squad', models.CharField(default='Swachhata Seva Squad 04', max_length=100)),
                ('reported_overflow_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_cleaned_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='nearbyresource',
            name='resource_type',
            field=models.CharField(choices=[('FOOD', 'Food / Annachatra'), ('WATER', 'Water Point'), ('TOILETS', 'Toilets'), ('RESTROOMS', 'Restrooms'), ('MEDICAL', 'Medical Camp'), ('DUSTBIN', 'Garbage Bin / Swachhata Point')], max_length=20),
        ),
    ]
