# Generated by Django 6.0.3 on 2026-08-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wari_core', '0003_nearbyresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyresource',
            name='resource_type',
            field=models.CharField(choices=[('FOOD', 'Food / Annachatra'), ('WATER', 'Water Point'), ('TOILETS', 'Toilets'), ('RESTROOMS', 'Restrooms'), ('MEDICAL', 'Medical Camp'), ('WASTE', 'Waste Management / Nirmal Wari')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sevaresource',
            name='category',
            field=models.CharField(choices=[('MEDICAL', 'Medical Camp & Ambulance'), ('WATER', 'Clean Drinking Water Point'), ('FOOD', 'Annachatra / Mahaprasad'), ('SHELTER', 'Night Shelter & Tent Ground'), ('SANITATION', 'Mobile Toilets & Sanitation'), ('WASTE', 'Waste Management & Nirmal Wari')], default='WATER', max_length=30),
        ),
    ]
